import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

import ReactQueryProvider from 'providers/reactQueryProvider'

// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
